FROM flink:1.14.3-scala_2.12-java11

# Establecer directorio de trabajo (un buen lugar para scripts de usuario)
WORKDIR /opt/flink/usrlib

# Copiar los requerimientos y el script del job
COPY requirements.txt .
COPY flink.py .

# Instalar las dependencias de Python (apache-flink)
# La imagen base de Flink ya incluye 'pip'
RUN pip install --no-cache-dir -r requirements.txt
